# tasks file for klousiaj.wso2-esb - centOS specific tasks

### On CentOS we use firewalld.
#- name: check if "{{ item }}" is installed
#  yum:
#    list="{{ item }}"
#  register: is_installed
#  with_items:
#   - zip
- name: install "{{ item }}" if not exist
  yum:
    name: "{{ item }}"
    state: latest
#  when:  (is_installed.results|length == 1) or (is_installed.results[1].yumstate != 'installed') 
  with_items:
   - zip
   - unzip

#- name: check that firewalld is running
#  become: true
#  become_method: sudo
#  service:
#    name: firewalld
#    enabled: yes
#    
#- name: update the firewall rules to allow access over the specified port
#  become: true
#  become_method: sudo
#  firewalld:
#    port: "{{ item }}/tcp"
#    permanent: yes
#    immediate: yes
#    state: enabled
#  with_items:
#    - "{{ wso2_app_http_port }}"
#    - "{{ wso2_app_https_port }}"
